language: nodejs
before_script:
- npm run setup
- npm run build
script:
- npm run build
after_success:
- npm run docs
- npm pack
branches:
  only:
  - master
  - dev
before_deploy:
- git config --local user.name "vandbt"
- git config --local user.email "sharkspin@gmail.com"
- git tag "$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)"
deploy:
- provider: pages
  skip-cleanup: true
  local_dir: dist/
  github-token: "$GITHUB_TOKEN"
  keep-history: true
  on:
    branch: dev
- provider: releases
  api_key: "$GITHUB_TOKEN"
  file_glob: true
  file: dist/**/*
  skip_cleanup: true
  on:
    tags: true